//go:build ignore

// Standalone demo: go run examples/htn_planner_demo.go
package main

import (
	"fmt"
	"log"

	"github.com/mparvin/octaai/pkg/capability"
	"github.com/mparvin/octaai/pkg/core"
	"github.com/mparvin/octaai/pkg/planner"
)

// This example demonstrates the new v2 HTN planner architecture
func main() {
	fmt.Println("=== OctaAI v2 HTN Planner Example ===")
	fmt.Println()

	// 1. Initialize capability registry
	capRegistry := core.NewCapabilityRegistry()
	if err := capability.RegisterBuiltinCapabilities(capRegistry); err != nil {
		log.Fatalf("Failed to register capabilities: %v", err)
	}

	fmt.Printf("Registered %d capabilities:\n", len(capRegistry.List()))
	for _, cap := range capRegistry.List() {
		fmt.Printf("  - %s: %s (cost: %s)\n", cap.ID, cap.Name, cap.Cost)
	}
	fmt.Println()

	// 2. Search for capabilities (demonstrating the registry)
	results := capRegistry.Search("filesystem")
	fmt.Printf("Capabilities matching 'filesystem': %d\n", len(results))
	for _, cap := range results {
		fmt.Printf("  - %s: %s\n", cap.ID, cap.Name)
	}
	fmt.Println()

	// 4. Create a goal
	goal := &core.Goal{
		ID:          "goal_001",
		Description: "Create a simple Python Flask web server with routes for /hello and /status",
		ProjectName: "flask-demo",
		State:       core.GoalStatePlanning,
	}

	fmt.Printf("Goal: %s\n", goal.Description)
	fmt.Println()

	// 6. Create a simple execution graph manually to demonstrate the structure
	// (In production, this would be generated by htnPlanner.Plan())
	graph := &planner.ExecutionGraph{
		ID:     "graph_001",
		GoalID: goal.ID,
		Nodes: []*planner.TaskNode{
			{
				ID:          "node_001",
				Description: "Setup Flask project structure",
				Type:        planner.NodeTypeSequential,
				Capability:  "coding.python",
				Status:      core.TaskStatusPending,
				ToolSequence: []*planner.ToolCall{
					{Tool: "filesystem.create_directory", Args: map[string]interface{}{"path": "flask-demo"}},
					{Tool: "filesystem.write_file", Args: map[string]interface{}{"path": "flask-demo/requirements.txt", "content": "Flask==2.0.1"}},
				},
				Estimate: &core.NodeEstimate{
					Tokens:          500,
					DurationSeconds: 5,
					Cost:            0.01,
					Confidence:      0.9,
				},
			},
			{
				ID:          "node_002",
				Description: "Implement /hello and /status routes",
				Type:        planner.NodeTypeSequential,
				Capability:  "coding.python",
				Status:      core.TaskStatusPending,
				DependsOn:   []string{"node_001"},
				ToolSequence: []*planner.ToolCall{
					{Tool: "filesystem.write_file", Args: map[string]interface{}{"path": "flask-demo/app.py", "content": "# Flask app code"}},
				},
				Estimate: &core.NodeEstimate{
					Tokens:          800,
					DurationSeconds: 10,
					Cost:            0.016,
					Confidence:      0.85,
				},
			},
			{
				ID:          "node_003",
				Description: "Test the Flask server",
				Type:        planner.NodeTypeSequential,
				Capability:  "coding.command",
				Status:      core.TaskStatusPending,
				DependsOn:   []string{"node_002"},
				ToolSequence: []*planner.ToolCall{
					{Tool: "command.run", Args: map[string]interface{}{"cmd": "python flask-demo/app.py", "cwd": "."}},
				},
				Estimate: &core.NodeEstimate{
					Tokens:          300,
					DurationSeconds: 3,
					Cost:            0.006,
					Confidence:      0.95,
				},
			},
		},
		Edges: []*planner.Dependency{
			{From: "node_001", To: "node_002", Type: planner.DependencyTypeSequential},
			{From: "node_002", To: "node_003", Type: planner.DependencyTypeSequential},
		},
		Metadata: &planner.GraphMetadata{
			Version: "1.0",
		},
	}

	fmt.Printf("\n=== Manually Created Execution Graph ===\n")
	fmt.Println("(In production, this would be generated by HTN planner)")
	fmt.Println()

	// 7. Display the execution graph
	fmt.Printf("\n=== Execution Graph ===\n")
	fmt.Printf("Graph ID: %s\n", graph.ID)
	fmt.Printf("Goal ID: %s\n", graph.GoalID)
	fmt.Printf("Total Nodes: %d\n", len(graph.Nodes))
	fmt.Printf("Total Edges: %d\n\n", len(graph.Edges))

	// Show nodes
	fmt.Println("Nodes:")
	for i, node := range graph.Nodes {
		fmt.Printf("  %d. [%s] %s\n", i+1, node.Type, node.Description)
		fmt.Printf("     ID: %s, Status: %s\n", node.ID, node.Status)
		if len(node.ToolSequence) > 0 {
			fmt.Printf("     Tools: %d tool calls\n", len(node.ToolSequence))
		}
		if node.Estimate != nil {
			fmt.Printf("     Estimate: %d tokens, %ds duration, $%.4f cost\n",
				node.Estimate.Tokens,
				node.Estimate.DurationSeconds,
				node.Estimate.Cost)
		}
		fmt.Println()
	}

	// Show dependencies
	fmt.Println("Dependencies:")
	for _, edge := range graph.Edges {
		fmt.Printf("  %s -> %s (%v)\n", edge.From, edge.To, edge.Type)
	}
	fmt.Println()

	// 8. Get ready nodes (nodes that can execute immediately)
	readyNodes := graph.GetReadyNodes()
	fmt.Printf("Ready to execute: %d nodes\n", len(readyNodes))
	for _, node := range readyNodes {
		fmt.Printf("  - %s: %s\n", node.ID, node.Description)
	}
	fmt.Println()

	// 9. Estimate total cost using the cost estimator
	costEstimator := planner.NewCostEstimator()
	costEstimator.EstimateGraph(graph)

	fmt.Println("=== Cost Estimate ===")
	if graph.Metadata != nil {
		fmt.Printf("Total Tokens: %d\n", graph.Metadata.TotalEstimatedTokens)
		fmt.Printf("Total Duration: %s\n", graph.Metadata.TotalEstimatedDuration)
		fmt.Printf("Total Cost: $%.4f\n", graph.Metadata.TotalEstimatedCost)
	}
	fmt.Println()

	// 10. Validate graph structure
	if err := graph.Validate(); err != nil {
		log.Fatalf("Graph validation failed: %v", err)
	}
	fmt.Println("✓ Graph validation passed")
	fmt.Println()

	fmt.Println("=== Next Steps ===")
	fmt.Println("This graph is now ready for execution by the DAG executor.")
	fmt.Println("The executor will:")
	fmt.Println(" o use the full HTN planner with real LLM:")
	fmt.Println("  ctx := context.Background()")
	fmt.Println("  capabilities := capRegistry.List()")
	fmt.Println("  graph, err := htnPlanner.Plan(ctx, goal, capabilities)")
	fmt.Println()
	fmt.Println("The generated graph would then be executed by the DAG executor:")
	fmt.Println("  1. Run ready nodes in topological order")
	fmt.Println("  2. Execute parallel batches concurrently (up to MaxParallel)")
	fmt.Println("  3. Update node status as execution progresses")
	fmt.Println("  4. Handle conditional branches and loops")
	fmt.Println("  5. Request approval for approval nodes")
	fmt.Println()
	fmt.Println("Enable v2 features in config.yaml:")
	fmt.Println("  features:")
	fmt.Println("    use_htn_planner: true")
	fmt.Println("    use_capabilities: true")
}

// Note: mockLLM is not used in this demo - we create the graph manually
// In production, the HTN planner would call the LLM to decompose goals and select tools
